name: IndomieGrow Private Engine
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Proxy Cache
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: proxy-cache
          if_no_artifact_found: warn
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm install puppeteer axios @faker-js/faker
      - name: Run Engine
        env:
          OTP_API_KEY: ${{ secrets.OTP_API_KEY }}
        run: node src/automation-runner.js
      - name: Upload Proxy Cache
        uses: actions/upload-artifact@v4
        with:
          name: proxy-cache
          path: src/used_proxies.json
env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
